export const CONTACTS_FORM_REQUEST = 'CONTACTS_FORM_REQUEST';
export const CONTACTS_FORM_SUCCESS = 'CONTACTS_FORM_SUCCESS';
export const CONTACTS_FORM_FAILURE = 'CONTACTS_FORM_FAILURE';
export const CONTACTS_FORM_RESET = 'CONTACTS_FORM_RESET';